config/routes.rb
Rails.application.routes.draw do
  
  resources :jobs do
    resource :cv
  end
  
  root      'jobs#index'

end

app/models/cv.rb
class Cv < ActiveRecord::Base
   belongs_to :job
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController

  def index
    @cvs = Cv.all
  end
  
  def new
    @job = Job.find(params[:job_id])
    @job_cv = @job.cv.new
  end
  
  def create
  end
  
  def show
    @cv = Cv.find(params[:id])
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
  end
  
  def new
    @job = Job.new
  end
  
  def create
    @job = Job.new(job_params)
    flash[:success] = "Job was created"
    if @job.save
      redirect_to :jobs
    end
  end
  
  def show  # leads to view
    @job = Job.find(params[:id])
  end
  
  def edit
    @job = Job.find(params[:id])
  end
  
  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:success] = "Job was edited"
      redirect_to :jobs  
    end
  end
  
  
  def destroy
    @job = Job.find(params[:id])
    if @job.destroy
      flash[:success] = "Job was deleted"
    else
      flash[:error] = "Error deleting Job"  
    end
    redirect_to :jobs
  end
  

  private
    def job_params
      params.require(:job).permit(:company, :position, :description, :deadline, :url)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/cvs/new.html.erb
<h1> Add New CV </h1>
<div class="pure-form pure-form-stacked">
<%= form_for @job_cv do |f|%>
  <%= f.label :cv_name %>
  <%= f.text_field :cv_name %>
  
  <%= f.label :cv_text %>
  <%= f.text_field :cv_text %>

  <%= f.submit "Attach CV" %>
<% end %>
</div>

app/views/jobs/edit.html.erb
<h1> Edit Job </h1>
<div class="pure-form pure-form-stacked">
<%= form_for @job do |f|%>
  <%= f.label :company %>
  <%= f.text_field :company %>
  
  <%= f.label :position %>
  <%= f.text_field :position %>
  
  <%= f.label :description %>
  <%= f.text_area :description, size: "60x12" %>

  <%= f.label :deadline %>
  <%= select_date Date.today, prefix: :deadline %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit "Edit Job" %>
<% end %>
</div>

app/views/jobs/index.html.erb
<h1> JobX </h1>

<%= link_to "Add Job", new_job_path %> 

<% @jobs.each do |j| %>
      <h2> <%= j.id %>. <%= link_to j.position, job_path(j) %></h2>
      <%= j.company %>
      <%= j.description %>
      <%= j.deadline %>
      
      <small>
      <%= link_to "Edit Job", edit_job_path(j.id) %>
      <%= link_to "Delete", job_path(j.id), method: :delete, data: { confirm: "You sure?" } %>
      <%= link_to "Add Note" %> 
      <%= link_to "Add CV", new_job_cv_path(j) %>
      </small>

<% end %>

app/views/jobs/new.html.erb
<h1> Add New Job </h1>
<div class="pure-form pure-form-stacked">
<%= form_for @job do |f|%>
  <%= f.label :company %>
  <%= f.text_field :company %>
  
  <%= f.label :position %>
  <%= f.text_field :position %>
  
  <%= f.label :description %>
  <%= f.text_area :description, size: "60x12" %>

  <%= f.label :deadline %>
  <%= select_date Date.today, prefix: :deadline %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit "Add Job" %>
<% end %>
</div>

app/views/jobs/show.html.erb
Company: <%= @job.company %>
Position: <%= @job.position %>
Description: <%= @job.description %>
Deadline: <%= @job.deadline %> 

--Add CV
--Use Template
--Edit Template (show diff tool here)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobX</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>